# Generated by Django 4.0.2 on 2022-02-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=2000)),
                ('price', models.FloatField()),
                ('main_image', models.ImageField(default='images/no_image_available.png', upload_to='')),
                ('category_set', models.ManyToManyField(blank=True, related_name='product_set', to='storefront_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('alt_text', models.CharField(blank=True, max_length=100)),
                ('product', models.ManyToManyField(blank=True, related_name='product_images', to='storefront_app.Product')),
            ],
        ),
    ]
